CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS records (kind TEXT NOT NULL, id TEXT NOT NULL, body TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY(kind,id));
CREATE TABLE IF NOT EXISTS cache (input_hash TEXT PRIMARY KEY, judgment_id TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS spending (id TEXT PRIMARY KEY, estimated REAL NOT NULL, charged REAL NOT NULL, created_epoch REAL NOT NULL);
CREATE TABLE IF NOT EXISTS leases (key TEXT PRIMARY KEY, owner TEXT NOT NULL, expires_epoch REAL NOT NULL);
INSERT OR IGNORE INTO schema_migrations(version) VALUES(1);
